/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PlotState = IDL.Variant({
  'empty' : IDL.Null,
  'growing' : IDL.Record({
    'plantedAt' : Time,
    'seedId' : IDL.Text,
    'harvestReady' : Time,
  }),
  'harvestable' : IDL.Record({ 'plantedAt' : Time, 'seedId' : IDL.Text }),
});
export const PlayerState = IDL.Record({
  'balance' : IDL.Int,
  'seedInventory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  'gardenPlots' : IDL.Vec(PlotState),
});
export const Seed = IDL.Record({
  'id' : IDL.Text,
  'growTimeSeconds' : IDL.Int,
  'seedCost' : IDL.Int,
  'name' : IDL.Text,
  'sellPrice' : IDL.Int,
  'emoji' : IDL.Text,
  'category' : IDL.Text,
});
export const SeedPack = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'seeds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
  'price' : IDL.Int,
});
export const GameData = IDL.Record({
  'seeds' : IDL.Vec(Seed),
  'packs' : IDL.Vec(SeedPack),
});

export const idlService = IDL.Service({
  'buyPack' : IDL.Func([IDL.Text], [PlayerState], []),
  'buySeed' : IDL.Func([IDL.Text], [PlayerState], []),
  'getGameData' : IDL.Func([], [GameData], []),
  'getPlayerState' : IDL.Func([], [PlayerState], []),
  'harvestPlot' : IDL.Func([IDL.Int], [PlayerState], []),
  'plantSeed' : IDL.Func([IDL.Int, IDL.Text], [PlayerState], []),
  'resetPlot' : IDL.Func([IDL.Int], [PlayerState], []),
  'sellCrop' : IDL.Func([IDL.Text, IDL.Int], [PlayerState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PlotState = IDL.Variant({
    'empty' : IDL.Null,
    'growing' : IDL.Record({
      'plantedAt' : Time,
      'seedId' : IDL.Text,
      'harvestReady' : Time,
    }),
    'harvestable' : IDL.Record({ 'plantedAt' : Time, 'seedId' : IDL.Text }),
  });
  const PlayerState = IDL.Record({
    'balance' : IDL.Int,
    'seedInventory' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
    'gardenPlots' : IDL.Vec(PlotState),
  });
  const Seed = IDL.Record({
    'id' : IDL.Text,
    'growTimeSeconds' : IDL.Int,
    'seedCost' : IDL.Int,
    'name' : IDL.Text,
    'sellPrice' : IDL.Int,
    'emoji' : IDL.Text,
    'category' : IDL.Text,
  });
  const SeedPack = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'seeds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
    'price' : IDL.Int,
  });
  const GameData = IDL.Record({
    'seeds' : IDL.Vec(Seed),
    'packs' : IDL.Vec(SeedPack),
  });
  
  return IDL.Service({
    'buyPack' : IDL.Func([IDL.Text], [PlayerState], []),
    'buySeed' : IDL.Func([IDL.Text], [PlayerState], []),
    'getGameData' : IDL.Func([], [GameData], []),
    'getPlayerState' : IDL.Func([], [PlayerState], []),
    'harvestPlot' : IDL.Func([IDL.Int], [PlayerState], []),
    'plantSeed' : IDL.Func([IDL.Int, IDL.Text], [PlayerState], []),
    'resetPlot' : IDL.Func([IDL.Int], [PlayerState], []),
    'sellCrop' : IDL.Func([IDL.Text, IDL.Int], [PlayerState], []),
  });
};

export const init = ({ IDL }) => { return []; };