/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GameData { 'seeds' : Array<Seed>, 'packs' : Array<SeedPack> }
export interface PlayerState {
  'balance' : bigint,
  'seedInventory' : Array<[string, bigint]>,
  'gardenPlots' : Array<PlotState>,
}
export type PlotState = { 'empty' : null } |
  {
    'growing' : { 'plantedAt' : Time, 'seedId' : string, 'harvestReady' : Time }
  } |
  { 'harvestable' : { 'plantedAt' : Time, 'seedId' : string } };
export interface Seed {
  'id' : string,
  'growTimeSeconds' : bigint,
  'seedCost' : bigint,
  'name' : string,
  'sellPrice' : bigint,
  'emoji' : string,
  'category' : string,
}
export interface SeedPack {
  'id' : string,
  'name' : string,
  'description' : string,
  'seeds' : Array<[string, bigint]>,
  'price' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'buyPack' : ActorMethod<[string], PlayerState>,
  'buySeed' : ActorMethod<[string], PlayerState>,
  'getGameData' : ActorMethod<[], GameData>,
  'getPlayerState' : ActorMethod<[], PlayerState>,
  'harvestPlot' : ActorMethod<[bigint], PlayerState>,
  'plantSeed' : ActorMethod<[bigint, string], PlayerState>,
  'resetPlot' : ActorMethod<[bigint], PlayerState>,
  'sellCrop' : ActorMethod<[string, bigint], PlayerState>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];