/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GameData {
    seeds: Array<Seed>;
    packs: Array<SeedPack>;
}
export interface Seed {
    id: string;
    growTimeSeconds: bigint;
    seedCost: bigint;
    name: string;
    sellPrice: bigint;
    emoji: string;
    category: string;
}
export interface SeedPack {
    id: string;
    name: string;
    description: string;
    seeds: Array<[string, bigint]>;
    price: bigint;
}
export type Time = bigint;
export type PlotState = {
    __kind__: "empty";
    empty: null;
} | {
    __kind__: "growing";
    growing: {
        plantedAt: Time;
        seedId: string;
        harvestReady: Time;
    };
} | {
    __kind__: "harvestable";
    harvestable: {
        plantedAt: Time;
        seedId: string;
    };
};
export interface PlayerState {
    balance: bigint;
    seedInventory: Array<[string, bigint]>;
    gardenPlots: Array<PlotState>;
}
export interface backendInterface {
    buyPack(packId: string): Promise<PlayerState>;
    buySeed(seedId: string): Promise<PlayerState>;
    getGameData(): Promise<GameData>;
    getPlayerState(): Promise<PlayerState>;
    harvestPlot(plotId: bigint): Promise<PlayerState>;
    plantSeed(plotId: bigint, seedId: string): Promise<PlayerState>;
    resetPlot(plotId: bigint): Promise<PlayerState>;
    sellCrop(seedId: string, quantity: bigint): Promise<PlayerState>;
}
import type { PlayerState as _PlayerState, PlotState as _PlotState, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async buyPack(arg0: string): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.buyPack(arg0);
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buyPack(arg0);
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async buySeed(arg0: string): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.buySeed(arg0);
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.buySeed(arg0);
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGameData(): Promise<GameData> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameData();
            return result;
        }
    }
    async getPlayerState(): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayerState();
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayerState();
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async harvestPlot(arg0: bigint): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.harvestPlot(arg0);
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.harvestPlot(arg0);
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async plantSeed(arg0: bigint, arg1: string): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.plantSeed(arg0, arg1);
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.plantSeed(arg0, arg1);
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetPlot(arg0: bigint): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPlot(arg0);
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPlot(arg0);
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async sellCrop(arg0: string, arg1: bigint): Promise<PlayerState> {
        if (this.processError) {
            try {
                const result = await this.actor.sellCrop(arg0, arg1);
                return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sellCrop(arg0, arg1);
            return from_candid_PlayerState_n1(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PlayerState_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlayerState): PlayerState {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_PlotState_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlotState): PlotState {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    balance: bigint;
    seedInventory: Array<[string, bigint]>;
    gardenPlots: Array<_PlotState>;
}): {
    balance: bigint;
    seedInventory: Array<[string, bigint]>;
    gardenPlots: Array<PlotState>;
} {
    return {
        balance: value.balance,
        seedInventory: value.seedInventory,
        gardenPlots: from_candid_vec_n3(_uploadFile, _downloadFile, value.gardenPlots)
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    empty: null;
} | {
    growing: {
        plantedAt: _Time;
        seedId: string;
        harvestReady: _Time;
    };
} | {
    harvestable: {
        plantedAt: _Time;
        seedId: string;
    };
}): {
    __kind__: "empty";
    empty: null;
} | {
    __kind__: "growing";
    growing: {
        plantedAt: Time;
        seedId: string;
        harvestReady: Time;
    };
} | {
    __kind__: "harvestable";
    harvestable: {
        plantedAt: Time;
        seedId: string;
    };
} {
    return "empty" in value ? {
        __kind__: "empty",
        empty: value.empty
    } : "growing" in value ? {
        __kind__: "growing",
        growing: value.growing
    } : "harvestable" in value ? {
        __kind__: "harvestable",
        harvestable: value.harvestable
    } : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlotState>): Array<PlotState> {
    return value.map((x)=>from_candid_PlotState_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
